name: Build Release

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.24.1"

            - name: Update package list
              run: sudo apt-get update

            - name: Install dependencies
              run: sudo apt-get install -y libayatana-appindicator3-dev

            - name: Build for Windows
              run: |
                  GOOS=windows GOARCH=amd64 go build -o bin/chore_thing-amd64.exe -ldflags "-H=windowsgui"

            - name: Build for Linux
              run: |
                  GOOS=linux GOARCH=amd64 go build -o bin/chore_thing-amd64-linux

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                  name: chore_thing-amd64.exe
                  path: bin/chore_thing-amd64.exe

            - name: Upload Linux artifact
              uses: actions/upload-artifact@v4
              with:
                  name: chore_thing-amd64-linux
                  path: bin/chore_thing-amd64-linux
