name: Build Release

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.24.1"

            - name: Run build script
              run: |
                  chmod +x build.sh  # Make sure the script is executable
                  ./build.sh  # Run your build script

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: binaries
                  path: bin/
